// Cross-language policy interop assertions.
//
// For every (policy, event) vector in spec/test-vectors/v0.1-policy-decisions.json,
// both SDKs must produce identical Decisions. If TS evaluator drifts from
// the committed vectors generated by Python, this test fails.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { evaluate } from "../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const VECTORS_FILE = join(
  __dirname,
  "..",
  "..",
  "spec",
  "test-vectors",
  "v0.1-policy-decisions.json",
);
const POLICIES_DIR = join(__dirname, "..", "..", "spec", "fixtures", "policies");

interface PolicyVector {
  name: string;
  policy_fixture: string;
  event: Record<string, unknown>;
  expected_decision: "allowed" | "blocked" | "logged_only";
  expected_rule_id: string;
  expected_annotate: Record<string, unknown>;
}

const vectors: PolicyVector[] = JSON.parse(readFileSync(VECTORS_FILE, "utf-8")).vectors;

describe("cross-language interop — policy DSL evaluation", () => {
  for (const v of vectors) {
    it(`vector "${v.name}"`, () => {
      const policy = JSON.parse(
        readFileSync(join(POLICIES_DIR, v.policy_fixture), "utf-8"),
      ) as Record<string, unknown>;
      const result = evaluate(policy, v.event);
      expect(result.decision).toBe(v.expected_decision);
      expect(result.rule_id).toBe(v.expected_rule_id);
      expect(result.annotate).toEqual(v.expected_annotate);
    });
  }
});
