// End-to-end sign/verify roundtrip tests for the TypeScript SDK.
//
// Mirrors the Python SDK's tests/test_roundtrip.py one-for-one. Same
// fixtures (loaded from the sibling spec repo), same assertions. Plus a
// cross-language interop block that asserts byte-for-byte equality with
// pre-computed vectors generated by the Python SDK.

import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  InvalidSignature,
  SchemaValidationError,
  buildSigningInput,
  canonicalize,
  generateKeyPair,
  sign,
  validate,
  verify,
} from "../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Fixtures live in the sibling spec repo's `fixtures/events/` directory,
// checked out at /openagp/spec/. We resolve relative to this test file.
const SPEC_FIXTURES = join(__dirname, "..", "..", "spec", "fixtures", "events");

const EVENT_FIXTURES = readdirSync(SPEC_FIXTURES)
  .filter((f) => /^\d{2}-.*\.json$/.test(f))
  .sort()
  .map((f) => join(SPEC_FIXTURES, f));

function loadJson<T = unknown>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

describe("fixtures discovery", () => {
  it("the spec repo's fixtures are present at ../../spec", () => {
    expect(EVENT_FIXTURES.length).toBeGreaterThan(0);
  });
});

describe("schema validation", () => {
  for (const path of EVENT_FIXTURES) {
    const name = path.split("/").pop()!;
    it(`fixture ${name} validates against the bundled event schema`, () => {
      const event = loadJson(path);
      expect(() => validate(event, "event")).not.toThrow();
    });
  }
});

describe("sign/verify roundtrip", () => {
  for (const path of EVENT_FIXTURES) {
    const name = path.split("/").pop()!;
    it(`fixture ${name} round-trips through sign + verify`, () => {
      const event = loadJson<{ signature: { key_id: string; value: string } }>(path);
      const keys = generateKeyPair();

      const signed = sign(event, {
        privateKeyB64: keys.privateKeyB64,
        keyId: event.signature.key_id,
      });

      const sig = signed.signature as { key_id: string; alg: string; value: string };
      expect(sig.value).not.toBe(event.signature.value);
      expect(sig.value).toHaveLength(88);

      expect(() => verify(signed, { publicKeyB64: keys.publicKeyB64 })).not.toThrow();
    });
  }
});

describe("tamper detection", () => {
  it("modifying a non-signature field after signing fails verification", () => {
    const event = loadJson<Record<string, unknown>>(EVENT_FIXTURES[0]!);
    const keys = generateKeyPair();
    const signed = sign(event, { privateKeyB64: keys.privateKeyB64, keyId: "test-key" });

    const tampered = structuredClone(signed) as { action: { tool_name?: string } };
    tampered.action.tool_name = "evil.tool";

    expect(() => verify(tampered, { publicKeyB64: keys.publicKeyB64 })).toThrow(InvalidSignature);
  });

  it("verifying with the wrong public key fails", () => {
    const event = loadJson<Record<string, unknown>>(EVENT_FIXTURES[0]!);
    const signer = generateKeyPair();
    const other = generateKeyPair();

    const signed = sign(event, { privateKeyB64: signer.privateKeyB64, keyId: "test-key" });

    expect(() => verify(signed, { publicKeyB64: other.publicKeyB64 })).toThrow(InvalidSignature);
  });

  it("non-Ed25519 alg values are rejected at verify time", () => {
    const event = loadJson<Record<string, unknown>>(EVENT_FIXTURES[0]!);
    const keys = generateKeyPair();
    const signed = sign(event, { privateKeyB64: keys.privateKeyB64, keyId: "test-key" }) as {
      signature: { alg: string };
    };
    signed.signature.alg = "RS256";

    expect(() => verify(signed, { publicKeyB64: keys.publicKeyB64 })).toThrow(
      // Either InvalidSignature (alg-check path) or SchemaValidationError
      // (schema enforces alg=const Ed25519). Both are correct rejection paths.
      /alg|Ed25519/i,
    );
  });
});

describe("RFC 8785 canonicalization", () => {
  it("is deterministic regardless of source key order", () => {
    const a = { b: 2, a: 1, c: [3, 2, 1] };
    const b = { a: 1, c: [3, 2, 1], b: 2 };
    expect(canonicalize(a)).toEqual(canonicalize(b));
  });

  it("strips insignificant whitespace from JSON input", () => {
    const a = JSON.parse('{"a":1,"b":2}');
    const b = JSON.parse('   {  "a"  :  1 ,  "b"  :  2  }   ');
    expect(canonicalize(a)).toEqual(canonicalize(b));
  });

  it("signing input omits signature.value (ADR 0001)", () => {
    const eventWithPlaceholder = {
      agp_version: "0.1",
      event_id: "evt_x",
      actor: { vendor: "x", agent_id: "y" },
      action: { type: "tool_call" },
      signature: { key_id: "k1", alg: "Ed25519", value: "PLACEHOLDER" },
    };
    const eventWithout = structuredClone(eventWithPlaceholder) as { signature: Record<string, unknown> };
    delete eventWithout.signature.value;

    const a = buildSigningInput(eventWithPlaceholder, "k1");
    const b = buildSigningInput(eventWithout, "k1");
    expect(a).toEqual(b);
  });
});

// === Cross-language interop ==================================================
// These vectors are generated by the Python reference SDK and committed to
// the spec repo. If TypeScript's canonicalize() or sign() produces different
// bytes for the same input, the protocol is broken.

const VECTORS_DIR = join(__dirname, "..", "..", "spec", "test-vectors");

function bytesToHex(b: Uint8Array): string {
  return Array.from(b)
    .map((x) => x.toString(16).padStart(2, "0"))
    .join("");
}

describe("cross-language interop — RFC 8785 canonicalization", () => {
  const vectors = loadJson<{
    vectors: { name: string; input: unknown; expected_canonical_utf8_hex: string }[];
  }>(join(VECTORS_DIR, "v0.1-canonicalization.json"));

  for (const v of vectors.vectors) {
    it(`canonicalization vector "${v.name}" matches Python reference bytes`, () => {
      const got = canonicalize(v.input);
      expect(bytesToHex(got)).toBe(v.expected_canonical_utf8_hex);
    });
  }
});

describe("cross-language interop — signing", () => {
  const data = loadJson<{
    test_keypair: { private_key_b64: string; public_key_b64: string };
    vectors: {
      name: string;
      input: Record<string, unknown>;
      key_id: string;
      expected_signing_input_utf8_hex: string;
      expected_signature_b64: string;
    }[];
  }>(join(VECTORS_DIR, "v0.1-signatures.json"));

  const { private_key_b64, public_key_b64 } = data.test_keypair;

  for (const v of data.vectors) {
    it(`vector "${v.name}": signing input bytes match`, () => {
      const got = buildSigningInput(v.input, v.key_id);
      expect(bytesToHex(got)).toBe(v.expected_signing_input_utf8_hex);
    });

    it(`vector "${v.name}": signature bytes match (Ed25519 is deterministic)`, () => {
      const signed = sign(v.input, { privateKeyB64: private_key_b64, keyId: v.key_id }) as {
        signature: { value: string };
      };
      expect(signed.signature.value).toBe(v.expected_signature_b64);
    });

    it(`vector "${v.name}": Python-produced signature verifies in TypeScript`, () => {
      // Construct the exact signed object Python would have produced
      const signed = {
        ...v.input,
        signature: {
          key_id: v.key_id,
          alg: "Ed25519",
          value: v.expected_signature_b64,
        },
      };
      expect(() => verify(signed, { publicKeyB64: public_key_b64 })).not.toThrow();
    });
  }
});
